/**
 * 天赋称号系统相关常量
 */

import { Talent, Title, TitleSetEffect, EncounterEvent, ExplorationLocation, Achievement, RealmType } from '../types';

export const TALENTS: Talent[] = [
  // ========== 体质（12个）==========
  // 普通（4个）
  {
    id: 'talent-ordinary',
    name: '凡体',
    description: '普通的修仙资质，没有任何特殊加成。',
    category: '体质',
    rarity: '普通',
    fateCost: 1,
    effects: {},
  },
  {
    id: 'talent-iron-bone',
    name: '铁骨',
    description: '骨骼坚硬如铁，防御和体魄提升。',
    category: '体质',
    rarity: '普通',
    fateCost: 1,
    effects: { defense: 15, physique: 10 },
  },
  {
    id: 'talent-stone-skin',
    name: '石肤',
    description: '皮肤坚韧如石，抗打击能力增强。',
    category: '体质',
    rarity: '普通',
    fateCost: 1,
    effects: { defense: 20, hp: 30 },
  },
  {
    id: 'talent-swift-body',
    name: '轻身',
    description: '身体轻盈，速度和体魄有所提升。',
    category: '体质',
    rarity: '普通',
    fateCost: 1,
    effects: { speed: 12, physique: 5 },
  },

  // 稀有（3个）
  {
    id: 'talent-jade-bone',
    name: '玉骨',
    description: '骨骼温润如玉，防御和气血大幅提升。',
    category: '体质',
    rarity: '稀有',
    fateCost: 2,
    effects: { defense: 25, hp: 80, physique: 15 },
  },
  {
    id: 'talent-phoenix-blood',
    name: '凤血',
    description: '血脉中蕴含凤凰之力，气血恢复力极强。',
    category: '体质',
    rarity: '稀有',
    fateCost: 2,
    effects: { hp: 120, spirit: 10 },
    specialAbility: {
      id: 'phoenix-rebirth',
      name: '浴火重生',
      description: '战斗中气血低于20%时，有30%几率恢复30%气血。',
      type: 'passive',
      effects: { healPercent: 0.3, triggerChance: 0.3 },
    },
  },
  {
    id: 'talent-tortoise-body',
    name: '玄龟体',
    description: '体质如万年玄龟，防御极高但速度略降。',
    category: '体质',
    rarity: '稀有',
    fateCost: 2,
    effects: { defense: 40, hp: 100, speed: -8 },
  },

  // 传说（3个）
  {
    id: 'talent-immortal-body',
    name: '仙体',
    description: '天生仙体，气血和防御大幅提升。',
    category: '体质',
    rarity: '传说',
    fateCost: 4,
    effects: { hp: 200, defense: 50, spirit: 15 },
  },
  {
    id: 'talent-vajra-body',
    name: '金刚不坏',
    description: '修成金刚不坏之体，防御极高且体魄惊人。',
    category: '体质',
    rarity: '传说',
    fateCost: 4,
    effects: { defense: 60, physique: 45, hp: 180 },
    specialAbility: {
      id: 'vajra-shield',
      name: '金刚护体',
      description: '战斗中有25%几率触发护体金光，减免50%伤害。',
      type: 'passive',
      effects: { damageMultiplier: 0.5, triggerChance: 0.25 },
    },
  },
  {
    id: 'talent-true-dragon',
    name: '真龙之躯',
    description: '拥有真龙血脉淬炼的躯体，体魄冠绝天下。',
    category: '体质',
    rarity: '传说',
    fateCost: 4,
    effects: { physique: 55, hp: 250, defense: 35 },
  },

  // 仙品（2个）
  {
    id: 'talent-dragon-blood',
    name: '龙血之躯',
    description: '体内流淌着上古龙族血脉，体魄和防御登峰造极。',
    category: '体质',
    rarity: '仙品',
    fateCost: 6,
    effects: { hp: 350, physique: 60, defense: 50, attack: 30 },
    specialAbility: {
      id: 'dragon-rage',
      name: '龙怒',
      description: '气血低于50%时触发龙怒，攻击力提升80%持续3回合。',
      type: 'skill',
      unlockRealm: '筑基',
      effects: { damageMultiplier: 1.8, triggerChance: 1.0 },
    },
  },
  {
    id: 'talent-chaos-body',
    name: '混沌之体',
    description: '传说中的混沌体质，万法不侵，诸邪退避。',
    category: '体质',
    rarity: '仙品',
    fateCost: 6,
    effects: { defense: 80, hp: 400, physique: 50, spirit: 30 },
    specialAbility: {
      id: 'chaos-shield',
      name: '混沌护体',
      description: '受到伤害时有30%几率完全免疫，并反弹20%伤害。',
      type: 'passive',
      unlockRealm: '金丹',
      effects: { damageMultiplier: 0, triggerChance: 0.3 },
    },
  },

  // ========== 悟性（10个）==========
  // 普通（3个）
  {
    id: 'talent-smart',
    name: '聪慧',
    description: '头脑灵活，学习能力略强。',
    category: '悟性',
    rarity: '普通',
    fateCost: 1,
    effects: { expRate: 0.05, spirit: 5 },
  },
  {
    id: 'talent-good-learner',
    name: '善学',
    description: '善于总结规律，修炼效率略高。',
    category: '悟性',
    rarity: '普通',
    fateCost: 1,
    effects: { expRate: 0.08 },
  },
  {
    id: 'talent-good-memory',
    name: '记忆超群',
    description: '记忆力惊人，对功法领悟更快。',
    category: '悟性',
    rarity: '普通',
    fateCost: 1,
    effects: { spirit: 12, expRate: 0.03 },
  },

  // 稀有（3个）
  {
    id: 'talent-enlightened',
    name: '顿悟',
    description: '偶有灵光一闪，修炼速度提升明显。',
    category: '悟性',
    rarity: '稀有',
    fateCost: 2,
    effects: { expRate: 0.12, spirit: 15 },
  },
  {
    id: 'talent-firm-dao',
    name: '道心坚定',
    description: '道心稳固，突破成功率更高。',
    category: '悟性',
    rarity: '稀有',
    fateCost: 2,
    effects: { spirit: 20, expRate: 0.08 },
    specialAbility: {
      id: 'firm-heart',
      name: '不动道心',
      description: '突破失败时额外增加15%下次突破成功率。',
      type: 'passive',
      effects: { triggerChance: 1.0 },
    },
  },
  {
    id: 'talent-fast-cultivation',
    name: '修炼奇才',
    description: '修炼天赋出众，修炼速度提升15%。',
    category: '悟性',
    rarity: '稀有',
    fateCost: 2,
    effects: { expRate: 0.15, spirit: 8 },
  },

  // 传说（2个）
  {
    id: 'talent-dao-mind',
    name: '道心通明',
    description: '道心如明镜，对天地法则有超凡感悟。',
    category: '悟性',
    rarity: '传说',
    fateCost: 4,
    effects: { expRate: 0.2, spirit: 35, luck: 10 },
    specialAbility: {
      id: 'instant-dao',
      name: '一念悟道',
      description: '打坐修炼时有15%几率进入顿悟状态，本次修炼经验翻倍。',
      type: 'passive',
      effects: { triggerChance: 0.15, damageMultiplier: 2.0 },
    },
  },
  {
    id: 'talent-genius',
    name: '修炼天才',
    description: '天生修炼之才，修炼速度大幅提升。',
    category: '悟性',
    rarity: '传说',
    fateCost: 4,
    effects: { expRate: 0.25, spirit: 40 },
  },

  // 仙品（2个）
  {
    id: 'talent-prodigy',
    name: '天纵之才',
    description: '万年难遇的绝世天才，修炼速度冠绝当世。',
    category: '悟性',
    rarity: '仙品',
    fateCost: 6,
    effects: { expRate: 0.35, spirit: 60, luck: 15 },
    specialAbility: {
      id: 'heavenly-insight',
      name: '天道感悟',
      description: '每次突破境界后获得大量经验奖励，且突破成功率永久+10%。',
      type: 'passive',
      effects: { triggerChance: 1.0 },
    },
  },
  {
    id: 'talent-great-dao',
    name: '大道至简',
    description: '领悟大道至简之理，化繁为简，修炼速度极快。',
    category: '悟性',
    rarity: '仙品',
    fateCost: 6,
    effects: { expRate: 0.3, spirit: 50, speed: 25 },
    specialAbility: {
      id: 'simplify-dao',
      name: '万法归一',
      description: '学习任何功法时直接获得满级效果，且功法效果提升30%。',
      type: 'passive',
      unlockRealm: '筑基',
      effects: { triggerChance: 1.0, damageMultiplier: 1.3 },
    },
  },

  // ========== 战斗（12个）==========
  // 普通（4个）
  {
    id: 'talent-sharp-strike',
    name: '锐击',
    description: '出手凌厉，攻击力略有提升。',
    category: '战斗',
    rarity: '普通',
    fateCost: 1,
    effects: { attack: 12 },
  },
  {
    id: 'talent-warlike',
    name: '好战',
    description: '天生好斗，攻击和速度略有提升。',
    category: '战斗',
    rarity: '普通',
    fateCost: 1,
    effects: { attack: 8, speed: 5 },
  },
  {
    id: 'talent-sword-fan',
    name: '剑痴',
    description: '对剑道有天然的亲近感，攻击提升。',
    category: '战斗',
    rarity: '普通',
    fateCost: 1,
    effects: { attack: 10, spirit: 3 },
  },
  {
    id: 'talent-nimble',
    name: '灵巧',
    description: '身手灵活，速度和攻击力有所提升。',
    category: '战斗',
    rarity: '普通',
    fateCost: 1,
    effects: { speed: 10, attack: 6 },
  },

  // 稀有（3个）
  {
    id: 'talent-berserker',
    name: '狂战',
    description: '越战越勇，攻击力大幅提升但防御略降。',
    category: '战斗',
    rarity: '稀有',
    fateCost: 2,
    effects: { attack: 35, defense: -10, speed: 5 },
    specialAbility: {
      id: 'battle-frenzy',
      name: '战斗狂热',
      description: '每击杀一个敌人，攻击力永久叠加3%（本局战斗内）。',
      type: 'passive',
      effects: { triggerChance: 1.0, damageMultiplier: 0.03 },
    },
  },
  {
    id: 'talent-sword-intent',
    name: '剑意初成',
    description: '领悟了初步的剑意，攻击凌厉无比。',
    category: '战斗',
    rarity: '稀有',
    fateCost: 2,
    effects: { attack: 30, speed: 10 },
  },
  {
    id: 'talent-blade-maniac',
    name: '刀狂',
    description: '以刀入道，攻击力极高但不够灵活。',
    category: '战斗',
    rarity: '稀有',
    fateCost: 2,
    effects: { attack: 40, speed: -5 },
  },

  // 传说（3个）
  {
    id: 'talent-sword-heart',
    name: '剑心通明',
    description: '心与剑合一，攻击力大幅提升。',
    category: '战斗',
    rarity: '传说',
    fateCost: 4,
    effects: { attack: 80, speed: 20, spirit: 15 },
    specialAbility: {
      id: 'ten-thousand-swords',
      name: '万剑归宗',
      description: '战斗中有20%几率释放万剑齐发，造成250%攻击伤害。',
      type: 'skill',
      unlockRealm: '金丹',
      effects: { damageMultiplier: 2.5, triggerChance: 0.2 },
    },
  },
  {
    id: 'talent-thunder-body',
    name: '雷体',
    description: '拥有雷属性体质，攻击附带雷电之力。',
    category: '战斗',
    rarity: '传说',
    fateCost: 4,
    effects: { attack: 70, speed: 35, spirit: 25 },
    specialAbility: {
      id: 'thunder-strike',
      name: '天雷轰顶',
      description: '攻击时有25%几率触发天雷，造成180%攻击伤害并眩晕敌人。',
      type: 'skill',
      effects: { damageMultiplier: 1.8, triggerChance: 0.25 },
    },
  },
  {
    id: 'talent-sword-saint',
    name: '剑圣之资',
    description: '天生剑道奇才，有望成就剑圣之位。',
    category: '战斗',
    rarity: '传说',
    fateCost: 4,
    effects: { attack: 90, speed: 15 },
  },

  // 仙品（2个）
  {
    id: 'talent-war-god',
    name: '战神之体',
    description: '上古战神血脉觉醒，战斗能力冠绝天下。',
    category: '战斗',
    rarity: '仙品',
    fateCost: 6,
    effects: { attack: 120, defense: 30, speed: 35, physique: 25 },
    specialAbility: {
      id: 'war-god-rage',
      name: '战神之怒',
      description: '进入狂暴状态，攻击力翻倍且免疫控制，持续3回合。每场战斗可触发一次。',
      type: 'skill',
      unlockRealm: '筑基',
      effects: { damageMultiplier: 2.0, triggerChance: 1.0 },
    },
  },
  {
    id: 'talent-destruction',
    name: '破灭之体',
    description: '毁灭之力寄宿体内，所过之处寸草不生。',
    category: '战斗',
    rarity: '仙品',
    fateCost: 6,
    effects: { attack: 150, speed: 25, hp: -100 },
    specialAbility: {
      id: 'annihilation',
      name: '湮灭',
      description: '攻击时15%几率触发湮灭效果，直接消灭敌人30%当前气血。',
      type: 'skill',
      unlockRealm: '金丹',
      effects: { damageMultiplier: 0.3, triggerChance: 0.15 },
    },
  },

  // ========== 气运（10个）==========
  // 普通（3个）
  {
    id: 'talent-lucky-basic',
    name: '幸运',
    description: '运气不错，偶有好事发生。',
    category: '气运',
    rarity: '普通',
    fateCost: 1,
    effects: { luck: 10 },
  },
  {
    id: 'talent-good-fate',
    name: '善缘',
    description: '与人为善，容易结交贵人。',
    category: '气运',
    rarity: '普通',
    fateCost: 1,
    effects: { luck: 8, spirit: 3 },
  },
  {
    id: 'talent-noble-help',
    name: '贵人相助',
    description: '命中有贵人，遇到困难时常得援助。',
    category: '气运',
    rarity: '普通',
    fateCost: 1,
    effects: { luck: 12 },
  },

  // 稀有（3个）
  {
    id: 'talent-fortune-star',
    name: '福星',
    description: '福星高照，幸运值大幅提升。',
    category: '气运',
    rarity: '稀有',
    fateCost: 2,
    effects: { luck: 25, expRate: 0.05 },
  },
  {
    id: 'talent-great-fortune',
    name: '鸿运当头',
    description: '气运鼎盛，更容易遇到奇遇和稀有事件。',
    category: '气运',
    rarity: '稀有',
    fateCost: 2,
    effects: { luck: 30, expRate: 0.08 },
    specialAbility: {
      id: 'fortune-encounter',
      name: '福缘深厚',
      description: '历练时触发奇遇的概率提升20%。',
      type: 'passive',
      effects: { triggerChance: 0.2 },
    },
  },
  {
    id: 'talent-auspicious',
    name: '天降祥瑞',
    description: '出生时天降祥瑞，命格不凡。',
    category: '气运',
    rarity: '稀有',
    fateCost: 2,
    effects: { luck: 20, spirit: 10, hp: 30 },
  },

  // 传说（2个）
  {
    id: 'talent-blessed',
    name: '天眷之人',
    description: '受天道眷顾，幸运值和修炼速度提升。',
    category: '气运',
    rarity: '传说',
    fateCost: 4,
    effects: { luck: 40, expRate: 0.15, spirit: 15 },
    specialAbility: {
      id: 'divine-blessing',
      name: '天佑',
      description: '每天有10%几率触发天佑事件，获得随机珍稀奖励。',
      type: 'event',
      effects: { triggerChance: 0.1, eventId: 'divine-blessing-event' },
    },
  },
  {
    id: 'talent-lucky-star',
    name: '气运加身',
    description: '气运浓厚，幸运值极高且修炼速度提升。',
    category: '气运',
    rarity: '传说',
    fateCost: 4,
    effects: { luck: 50, expRate: 0.12 },
  },

  // 仙品（2个）
  {
    id: 'talent-heaven-child',
    name: '天运之子',
    description: '受天道钟爱的天之骄子，气运逆天。',
    category: '气运',
    rarity: '仙品',
    fateCost: 6,
    effects: { luck: 60, expRate: 0.2, spirit: 25 },
    specialAbility: {
      id: 'heaven-favored',
      name: '天命所归',
      description: '历练时必定触发奇遇，且奇遇品质提升一个等级。每日可触发一次。',
      type: 'event',
      effects: { triggerChance: 1.0, eventId: 'heaven-event' },
    },
  },
  {
    id: 'talent-indestructible',
    name: '万劫不灭',
    description: '万劫加身而不灭，命运已超脱轮回。',
    category: '气运',
    rarity: '仙品',
    fateCost: 6,
    effects: { luck: 45, defense: 40, hp: 200, expRate: 0.15 },
    specialAbility: {
      id: 'escape-death',
      name: '死里逃生',
      description: '致死攻击时有50%几率保留1点气血并免疫后续伤害一回合。',
      type: 'passive',
      unlockRealm: '筑基',
      effects: { triggerChance: 0.5 },
    },
  },

  // ========== 特殊（8个）==========
  // 普通（2个）
  {
    id: 'talent-herb-spirit',
    name: '药灵',
    description: '天生与灵药亲近，炼丹效率更高。',
    category: '特殊',
    rarity: '普通',
    fateCost: 1,
    effects: { spirit: 8, luck: 5 },
    specialAbility: {
      id: 'alchemy-boost',
      name: '灵药亲和',
      description: '炼丹时成功率提升15%，有概率获得额外丹药。',
      type: 'passive',
      effects: { triggerChance: 0.15 },
    },
  },
  {
    id: 'talent-forge-talent',
    name: '炼器天赋',
    description: '天生适合炼器，装备更容易获得好属性。',
    category: '特殊',
    rarity: '普通',
    fateCost: 1,
    effects: { spirit: 5, physique: 8 },
    specialAbility: {
      id: 'forge-mastery',
      name: '器道通神',
      description: '炼器时品质提升一个等级，且有20%概率额外产出。',
      type: 'passive',
      effects: { triggerChance: 0.2 },
    },
  },

  // 稀有（2个）
  {
    id: 'talent-dao-companion',
    name: '天生道侣',
    description: '命中注定有道侣相伴，修炼效率提升。',
    category: '特殊',
    rarity: '稀有',
    fateCost: 2,
    effects: { expRate: 0.1, spirit: 12, luck: 8 },
    specialAbility: {
      id: 'companion-bond',
      name: '道侣同心',
      description: '触发双修事件时经验加成提升50%。',
      type: 'event',
      effects: { triggerChance: 1.0, eventId: 'companion-event' },
    },
  },
  {
    id: 'talent-past-life-memory',
    name: '前世记忆',
    description: '隐约记得前世的修炼经验。',
    category: '特殊',
    rarity: '稀有',
    fateCost: 2,
    effects: { expRate: 0.12, spirit: 15 },
    specialAbility: {
      id: 'past-wisdom',
      name: '前世传承',
      description: '解锁前世记忆事件链，获得额外修炼传承。',
      type: 'event',
      effects: { triggerChance: 1.0, eventId: 'past-life-event' },
    },
  },

  // 传说（2个）
  {
    id: 'talent-dual-cultivation',
    name: '双修之体',
    description: '天生适合双修，与人合修时效率极高。',
    category: '特殊',
    rarity: '传说',
    fateCost: 4,
    effects: { expRate: 0.18, spirit: 25, hp: 80 },
    specialAbility: {
      id: 'dual-mastery',
      name: '阴阳调和',
      description: '双修时经验获取翻倍，且有概率获得对方天赋的部分加成。',
      type: 'passive',
      unlockRealm: '筑基',
      effects: { triggerChance: 1.0, damageMultiplier: 2.0 },
    },
  },
  {
    id: 'talent-all-spirits',
    name: '万灵之体',
    description: '能与万灵沟通，灵宠亲和度极高。',
    category: '特殊',
    rarity: '传说',
    fateCost: 4,
    effects: { spirit: 35, luck: 20, hp: 100 },
    specialAbility: {
      id: 'spirit-bond',
      name: '万灵归心',
      description: '捕获灵宠概率提升50%，灵宠属性加成提升30%。',
      type: 'passive',
      effects: { triggerChance: 1.0, damageMultiplier: 1.3 },
    },
  },

  // 仙品（2个）
  {
    id: 'talent-immortal-king',
    name: '仙王转世',
    description: '疑似仙王转世，各项属性大幅提升，修炼速度极快。',
    category: '特殊',
    rarity: '仙品',
    fateCost: 6,
    effects: {
      attack: 80,
      defense: 60,
      hp: 300,
      spirit: 50,
      physique: 40,
      speed: 35,
      expRate: 0.3,
    },
    specialAbility: {
      id: 'immortal-memory',
      name: '仙王记忆',
      description: '随境界提升逐步觉醒前世记忆，每突破一个大境界获得大量经验和属性奖励。',
      type: 'event',
      effects: { triggerChance: 1.0, eventId: 'immortal-awakening' },
    },
  },
  {
    id: 'talent-balanced',
    name: '天道均衡',
    description: '暗合天道均衡之理，各项属性全面提升。',
    category: '特殊',
    rarity: '仙品',
    fateCost: 6,
    effects: {
      attack: 60,
      defense: 60,
      hp: 250,
      spirit: 45,
      physique: 45,
      speed: 30,
      expRate: 0.2,
      luck: 25,
    },
    specialAbility: {
      id: 'balance-dao',
      name: '天道均衡',
      description: '所有属性加成效果提升20%，且不存在任何属性短板。',
      type: 'passive',
      effects: { triggerChance: 1.0, damageMultiplier: 1.2 },
    },
  },
];

// --- 角色系统：称号 ---
export const TITLES: Title[] = [
  {
    id: 'title-novice',
    name: '初入仙途',
    description: '刚刚踏入修仙之路的新人。',
    requirement: '初始称号',
    effects: {},
  },
  {
    id: 'title-foundation',
    name: '筑基修士',
    description: '成功筑基，正式踏入修仙门槛。',
    requirement: '达到筑基期',
    effects: { attack: 10, defense: 5 },
  },
  {
    id: 'title-golden-core',
    name: '金丹真人',
    description: '凝聚金丹，已是修仙界的中流砥柱。',
    requirement: '达到金丹期',
    effects: { attack: 50, defense: 25, hp: 200 },
  },
  {
    id: 'title-nascent-soul',
    name: '元婴老祖',
    description: '修成元婴，可称一方老祖。',
    requirement: '达到元婴期',
    effects: { attack: 200, defense: 100, hp: 1000 },
  },
  {
    id: 'title-immortal',
    name: '飞升仙人',
    description: '渡劫飞升，已是真正的仙人。',
    requirement: '达到渡劫飞升',
    category: 'cultivation',
    rarity: '仙品',
    effects: { attack: 1000, defense: 500, hp: 5000, expRate: 0.3 },
  },
  // 战斗类称号
  {
    id: 'title-warrior',
    name: '战士',
    description: '在战斗中展现出色实力。',
    requirement: '击败10个敌人',
    category: 'combat',
    rarity: '普通',
    setGroup: 'warrior',
    effects: { attack: 15, defense: 5 },
  },
  {
    id: 'title-slayer',
    name: '屠戮者',
    description: '击败大量敌人的战士。',
    requirement: '击败50个敌人',
    category: 'combat',
    rarity: '稀有',
    setGroup: 'warrior',
    effects: { attack: 50, defense: 20, hp: 100 },
  },
  {
    id: 'title-champion',
    name: '战神',
    description: '战无不胜的绝世强者。',
    requirement: '击败100个敌人',
    category: 'combat',
    rarity: '传说',
    setGroup: 'warrior',
    effects: { attack: 150, defense: 75, hp: 500, speed: 20 },
  },
  // 探索类称号
  {
    id: 'title-explorer',
    name: '探索者',
    description: '对未知世界充满好奇。',
    requirement: '完成20次历练',
    category: 'exploration',
    rarity: '普通',
    setGroup: 'explorer',
    effects: { spirit: 10, luck: 5 },
  },
  {
    id: 'title-adventurer',
    name: '冒险家',
    description: '历经无数冒险的探险者。',
    requirement: '完成50次历练',
    category: 'exploration',
    rarity: '稀有',
    setGroup: 'explorer',
    effects: { spirit: 30, luck: 15, expRate: 0.1 },
  },
  {
    id: 'title-traveler',
    name: '游历者',
    description: '走遍天下的旅人。',
    requirement: '完成100次历练',
    category: 'exploration',
    rarity: '传说',
    setGroup: 'explorer',
    effects: { spirit: 80, luck: 30, expRate: 0.15, speed: 15 },
  },
  // 收集类称号
  {
    id: 'title-collector',
    name: '收藏家',
    description: '喜欢收集各种物品。',
    requirement: '收集10种物品',
    category: 'collection',
    rarity: '普通',
    setGroup: 'collector',
    effects: { luck: 10 },
  },
  {
    id: 'title-hoarder',
    name: '囤积者',
    description: '拥有大量收藏品。',
    requirement: '收集30种物品',
    category: 'collection',
    rarity: '稀有',
    setGroup: 'collector',
    effects: { luck: 25, spirit: 20 },
  },
  {
    id: 'title-treasurer',
    name: '珍宝收藏家',
    description: '拥有无数珍稀收藏品。',
    requirement: '收集50种物品',
    category: 'collection',
    rarity: '传说',
    setGroup: 'collector',
    effects: { luck: 50, spirit: 50, expRate: 0.1 },
  },
  // 特殊类称号
  {
    id: 'title-hermit',
    name: '隐士',
    description: '长期闭关修炼的隐士。',
    requirement: '完成100次打坐',
    category: 'cultivation',
    rarity: '稀有',
    effects: { expRate: 0.2, spirit: 40, physique: 30 },
  },
  {
    id: 'title-alchemist',
    name: '炼丹大师',
    description: '精通炼丹之术。',
    requirement: '炼制20次丹药',
    category: 'special',
    rarity: '稀有',
    effects: { spirit: 30, luck: 15 },
  },
  {
    id: 'title-sect-master',
    name: '宗门主事',
    description: '担任过宗门长老。',
    requirement: '达到长老职位',
    category: 'special',
    rarity: '传说',
    effects: { attack: 100, defense: 100, spirit: 50, expRate: 0.15 },
  },
];

// 称号套装效果
export const TITLE_SET_EFFECTS: TitleSetEffect[] = [
  {
    setName: '战士套装',
    titles: ['title-warrior', 'title-slayer', 'title-champion'],
    description: '佩戴所有战士称号，获得强大的战斗加成',
    effects: {
      attack: 100,
      defense: 50,
      hp: 300,
      speed: 10,
    },
  },
  {
    setName: '探索者套装',
    titles: ['title-explorer', 'title-adventurer', 'title-traveler'],
    description: '佩戴所有探索者称号，提升探索收益',
    effects: {
      spirit: 50,
      luck: 40,
      expRate: 0.2,
      speed: 15,
    },
  },
  {
    setName: '收藏家套装',
    titles: ['title-collector', 'title-hoarder', 'title-treasurer'],
    description: '佩戴所有收藏家称号，大幅提升幸运值',
    effects: {
      luck: 80,
      spirit: 60,
      expRate: 0.15,
    },
  },
];

// --- 奇遇系统 ---
export const ENCOUNTER_EVENTS: EncounterEvent[] = [
  {
    id: 'encounter-herb',
    name: '发现灵草',
    description: '你在山间发现了一株珍贵的灵草。',
    rarity: '普通',
    triggerChance: 0.3,
    rewards: {
      exp: 20,
      items: [{ name: '聚灵草', rarity: '普通', quantity: 1 }],
    },
  },
  {
    id: 'encounter-spirit-stone',
    name: '灵石矿脉',
    description: '你意外发现了一处小型灵石矿脉。',
    rarity: '稀有',
    triggerChance: 0.15,
    rewards: {
      spiritStones: 100,
      exp: 50,
    },
  },
  {
    id: 'encounter-ancient-cave',
    name: '古修士洞府',
    description: '你发现了一处古修士遗留的洞府，获得了珍贵的传承。',
    rarity: '传说',
    triggerChance: 0.05,
    minRealm: RealmType.Foundation,
    requirements: { minLuck: 30 },
    rewards: {
      exp: 500,
      spiritStones: 500,
      items: [{ name: '上古功法残卷', rarity: '传说', quantity: 1 }],
    },
  },
  {
    id: 'encounter-immortal-herb',
    name: '万年仙草',
    description: '你遇到了传说中的万年仙草，这是天大的机缘！',
    rarity: '仙品',
    triggerChance: 0.01,
    minRealm: RealmType.GoldenCore,
    requirements: { minLuck: 50 },
    rewards: {
      exp: 2000,
      items: [{ name: '万年仙草', rarity: '仙品', quantity: 1 }],
    },
  },
];

// --- 探索系统 ---
export const EXPLORATION_LOCATIONS: ExplorationLocation[] = [
  {
    id: 'explore-forest',
    name: '迷雾森林',
    description: '常年被迷雾笼罩的森林，隐藏着许多秘密。',
    minRealm: RealmType.QiRefining,
    cost: 20,
    riskLevel: '低',
    eventTypes: ['normal', 'lucky'],
  },
  {
    id: 'explore-mountain',
    name: '天柱山',
    description: '高耸入云的山峰，传说有仙人居住。',
    minRealm: RealmType.Foundation,
    cost: 50,
    riskLevel: '中',
    eventTypes: ['normal', 'lucky'],
    specialEncounters: ['encounter-ancient-cave'],
  },
  {
    id: 'explore-abyss',
    name: '无底深渊',
    description: '深不见底的深渊，危险与机遇并存。',
    minRealm: RealmType.GoldenCore,
    cost: 200,
    riskLevel: '高',
    eventTypes: ['normal', 'lucky', 'secret_realm'],
    specialEncounters: ['encounter-immortal-herb'],
  },
];

// --- 成就系统 ---
export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-first-step',
    name: '第一步',
    description: '完成第一次打坐修炼',
    category: 'cultivation',
    requirement: { type: 'custom', value: 1, target: 'meditate' },
    reward: { exp: 50, spiritStones: 10 },
    rarity: '普通',
  },
  {
    id: 'ach-foundation',
    name: '筑基成功',
    description: '突破到筑基期',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.Foundation },
    reward: { exp: 500, spiritStones: 200, titleId: 'title-foundation' },
    rarity: '稀有',
  },
  {
    id: 'ach-golden-core',
    name: '金丹大道',
    description: '突破到金丹期',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.GoldenCore },
    reward: { exp: 2000, spiritStones: 1000, titleId: 'title-golden-core' },
    rarity: '传说',
  },
  {
    id: 'ach-first-kill',
    name: '初战告捷',
    description: '在历练中击败第一个敌人',
    category: 'combat',
    requirement: { type: 'kill', value: 1 },
    reward: { exp: 100, spiritStones: 50 },
    rarity: '普通',
  },
  {
    id: 'ach-killer-10',
    name: '十人斩',
    description: '击败10个敌人',
    category: 'combat',
    requirement: { type: 'kill', value: 10 },
    reward: { exp: 200, spiritStones: 100, titleId: 'title-warrior' },
    rarity: '普通',
  },
  {
    id: 'ach-killer-50',
    name: '百战不殆',
    description: '击败50个敌人',
    category: 'combat',
    requirement: { type: 'kill', value: 50 },
    reward: { exp: 1000, spiritStones: 500, titleId: 'title-slayer' },
    rarity: '稀有',
  },
  {
    id: 'ach-killer-100',
    name: '千人斩',
    description: '击败100个敌人',
    category: 'combat',
    requirement: { type: 'kill', value: 100 },
    reward: { exp: 3000, spiritStones: 1500, titleId: 'title-champion' },
    rarity: '传说',
  },
  {
    id: 'ach-collector',
    name: '收藏家',
    description: '收集10种不同的物品',
    category: 'collection',
    requirement: { type: 'collect', value: 10 },
    reward: { exp: 300, spiritStones: 200, titleId: 'title-collector' },
    rarity: '稀有',
  },
  {
    id: 'ach-collector-20',
    name: '物品收藏家',
    description: '收集20种不同的物品',
    category: 'collection',
    requirement: { type: 'collect', value: 20 },
    reward: { exp: 500, spiritStones: 300, titleId: 'title-hoarder' },
    rarity: '稀有',
  },
  {
    id: 'ach-collector-50',
    name: '收藏大师',
    description: '收集50种不同的物品',
    category: 'collection',
    requirement: { type: 'collect', value: 50 },
    reward: { exp: 2000, spiritStones: 1000, titleId: 'title-treasurer' },
    rarity: '传说',
  },
  {
    id: 'ach-adventure-20',
    name: '历练新手',
    description: '完成20次历练',
    category: 'exploration',
    requirement: { type: 'adventure', value: 20 },
    reward: { exp: 300, spiritStones: 150, titleId: 'title-explorer' },
    rarity: '普通',
  },
  {
    id: 'ach-adventure-50',
    name: '冒险达人',
    description: '完成50次历练',
    category: 'exploration',
    requirement: { type: 'adventure', value: 50 },
    reward: { exp: 800, spiritStones: 400, titleId: 'title-adventurer' },
    rarity: '稀有',
  },
  {
    id: 'ach-adventure-100',
    name: '历练老手',
    description: '完成100次历练',
    category: 'exploration',
    requirement: { type: 'adventure', value: 100 },
    reward: { exp: 1500, spiritStones: 800, titleId: 'title-traveler' },
    rarity: '稀有',
  },
  {
    id: 'ach-meditate-100',
    name: '道心坚定',
    description: '完成100次打坐修炼',
    category: 'cultivation',
    requirement: { type: 'meditate', value: 100 },
    reward: { exp: 2000, spiritStones: 1000, titleId: 'title-hermit' },
    rarity: '传说',
  },
  {
    id: 'ach-meditate-20',
    name: '静心入定',
    description: '完成20次打坐修炼',
    category: 'cultivation',
    requirement: { type: 'meditate', value: 20 },
    reward: { exp: 400, spiritStones: 200 },
    rarity: '普通',
  },
  {
    id: 'ach-meditate-500',
    name: '坐忘无我',
    description: '完成500次打坐修炼',
    category: 'cultivation',
    requirement: { type: 'meditate', value: 500 },
    reward: { exp: 6000, spiritStones: 3000 },
    rarity: '稀有',
  },
  {
    id: 'ach-equip-5',
    name: '装备齐全',
    description: '装备5件物品',
    category: 'collection',
    requirement: { type: 'equip', value: 5 },
    reward: { exp: 200, spiritStones: 100 },
    rarity: '普通',
  },
  {
    id: 'ach-pet-1',
    name: '灵宠伙伴',
    description: '获得第一个灵宠',
    category: 'special',
    requirement: { type: 'pet', value: 1 },
    reward: { exp: 500, spiritStones: 200 },
    rarity: '稀有',
  },
  {
    id: 'ach-pet-3',
    name: '灵宠大师',
    description: '获得3个灵宠',
    category: 'special',
    requirement: { type: 'pet', value: 3 },
    reward: { exp: 1500, spiritStones: 800 },
    rarity: '传说',
  },
  {
    id: 'ach-recipe-5',
    name: '丹道入门',
    description: '解锁5个丹方',
    category: 'collection',
    requirement: { type: 'recipe', value: 5 },
    reward: { exp: 400, spiritStones: 200 },
    rarity: '稀有',
  },
  {
    id: 'ach-art-3',
    name: '功法初成',
    description: '学习3种功法',
    category: 'cultivation',
    requirement: { type: 'art', value: 3 },
    reward: { exp: 600, spiritStones: 300 },
    rarity: '稀有',
  },
  {
    id: 'ach-art-10',
    name: '功法大成',
    description: '学习10种功法',
    category: 'cultivation',
    requirement: { type: 'art', value: 10 },
    reward: { exp: 3000, spiritStones: 1500 },
    rarity: '传说',
  },
  {
    id: 'ach-breakthrough-5',
    name: '突破达人',
    description: '完成5次突破',
    category: 'cultivation',
    requirement: { type: 'breakthrough', value: 5 },
    reward: { exp: 1000, spiritStones: 500 },
    rarity: '稀有',
  },
  {
    id: 'ach-secret-realm-5',
    name: '秘境探索者',
    description: '进入5次秘境',
    category: 'exploration',
    requirement: { type: 'secret_realm', value: 5 },
    reward: { exp: 2000, spiritStones: 1000 },
    rarity: '传说',
  },
  {
    id: 'ach-secret-realm-20',
    name: '秘境行者',
    description: '进入20次秘境',
    category: 'exploration',
    requirement: { type: 'secret_realm', value: 20 },
    reward: { exp: 8000, spiritStones: 4000 },
    rarity: '传说',
  },
  {
    id: 'ach-lottery-10',
    name: '抽奖新手',
    description: '进行10次抽奖',
    category: 'special',
    requirement: { type: 'lottery', value: 10 },
    reward: { exp: 300, spiritStones: 200 },
    rarity: '普通',
  },
  {
    id: 'ach-lottery-50',
    name: '抽奖达人',
    description: '进行50次抽奖',
    category: 'special',
    requirement: { type: 'lottery', value: 50 },
    reward: { exp: 2000, spiritStones: 1500 },
    rarity: '稀有',
  },
  {
    id: 'ach-lottery-100',
    name: '抽奖痴迷',
    description: '进行100次抽奖',
    category: 'special',
    requirement: { type: 'lottery', value: 100 },
    reward: { exp: 5000, spiritStones: 4000 },
    rarity: '传说',
  },
  {
    id: 'ach-alchemy-20',
    name: '炼丹宗师',
    description: '成功炼制20次丹药',
    category: 'special',
    requirement: { type: 'custom', value: 20, target: 'alchemy' },
    reward: { exp: 1000, spiritStones: 1000, titleId: 'title-alchemist' },
    rarity: '传说',
  },
  {
    id: 'ach-sect-master',
    name: '宗门砥柱',
    description: '在宗门内晋升至长老或以上职位',
    category: 'special',
    requirement: { type: 'custom', value: 1, target: 'sect_elder' },
    reward: { exp: 2000, spiritStones: 2000, titleId: 'title-sect-master' },
    rarity: '传说',
  },
  {
    id: 'ach-nascent-soul',
    name: '元婴初成',
    description: '突破到元婴期',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.NascentSoul },
    reward: { exp: 5000, spiritStones: 3000, titleId: 'title-nascent-soul' },
    rarity: '传说',
  },
  {
    id: 'ach-spirit-severing',
    name: '化神大能',
    description: '突破到化神期',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.SpiritSevering },
    reward: { exp: 8000, spiritStones: 5000 },
    rarity: '传说',
  },
  {
    id: 'ach-dao-combining',
    name: '合道之主',
    description: '突破到合道期',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.DaoCombining },
    reward: { exp: 12000, spiritStones: 8000 },
    rarity: '传说',
  },
  {
    id: 'ach-longevity-realm',
    name: '长生久视',
    description: '突破到长生境',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.LongevityRealm },
    reward: { exp: 20000, spiritStones: 15000, titleId: 'title-immortal' },
    rarity: '仙品',
  },
];
